{
 "title": "AppLogs",
 "tags": [
  "Loki",
  "Alloy"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "FATAL ERROR WARN",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"app1_logs\", host=\"windows_vm\"} |= `FATAL` [$__auto]))",
     "legendFormat": "FATAL"
    },
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"app1_logs\", host=\"windows_vm\"} |= `ERROR` [$__auto]))",
     "legendFormat": "ERROR"
    },
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"app1_logs\", host=\"windows_vm\"} |= `WARN` [$__auto]))",
     "legendFormat": "WARN"
    }
   ]
  },
  {
   "title": "Logs FATAL ERROR WARN",
   "type": "logs",
   "gridPos": { "h": 10, "w": 15, "x": 9, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"app1_logs\", host=\"windows_vm\"} |= `WARN` or `ERROR` or `FATAL`"
    }
   ]
  },
  {
   "title": "FATAL",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 10 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"app1_logs\", host=\"windows_vm\"} |= `FATAL` [$__auto]))",
     "legendFormat": "FATAL"
    }
   ]
  },
  {
   "title": "Logs FATAL",
   "type": "logs",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 10 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"app1_logs\", host=\"windows_vm\"} |= `FATAL`"
    }
   ]
  },
  {
   "title": "ERROR",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 18 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"app1_logs\", host=\"windows_vm\"} |= `ERROR` [$__auto]))",
     "legendFormat": "ERROR"
    }
   ]
  },
  {
   "title": "Logs ERROR",
   "type": "logs",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 18 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"app1_logs\", host=\"windows_vm\"} |= `ERROR`"
    }
   ]
  },
  {
   "title": "WARN",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 26 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"app1_logs\", host=\"windows_vm\"} |= `WARN` [$__auto]))",
     "legendFormat": "WARN"
    }
   ]
  },
  {
   "title": "Logs WARN",
   "type": "logs",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 26 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"app1_logs\", host=\"windows_vm\"} |= `WARN`"
    }
   ]
  },
  {
   "title": "Logs FATAL ERROR WARN unwrap",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "direction": "forward",
     "expr": "{job=\"app1_logs\", host=\"windows_vm\"} | detected_level =~ \"unknown|FATAL|ERROR|WARN\""
    }
   ]
  },
  {
   "title": "Logs All",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"app1_logs\", host=\"windows_vm\"}"
    }
   ]
  },
  {
   "title": "App2",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{host=\"windows_vm\", job=\"app2_logs\"} |= ``"
    }
   ]
  }
 ]
}